apiVersion: v1
kind: Pod
metadata:
  labels:
    run: nginx
    storage: temp-volume
    method: fromcode
  name: nginx-storage
spec:
  containers:
    - image: nginx
      name: nginx
      volumeMounts:
        - name: scratch-volume
          mountPath: /scratch
    - image: busybox
      name: busybox
      command: ["/bin/sh", "-c"]
      args: ["sleep 1000"]
      volumeMounts:
        - name: scratch-volume
          mountPath: /scratch

  volumes:
    - name: scratch-volume
      emptyDir:
        sizeLimit: 500Mi
