apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: test-deploy-label
  name: test-deploy
spec:
  replicas: 10
  selector:
    matchLabels:
      app: test-deploy
  template:
    metadata:
      labels:
        app: test-deploy
    spec:
      containers:
      - image: httpd:alpine
        name: httpd
        # simulate a pod failure by exiting with 1
        # command: ["/bin/bash","-c","sleep 5; exit 1"]
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1

