apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mealie-pvc
  namespace: mealie
spec:
  accessModes:
    - ReadWriteOnce
  # the Persistent Volume is created on the fly
  resources:
    requests:
      storage: 500Mi
