apiVersion: v1
kind: Namespace
metadata:
  name: database
  labels:
    name: database

---
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: demo-cluster
  namespace: database
spec:
  instances: 3

  storage:
    size: 1Gi

